"""Browser UI markup for the local API."""

HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Local AI Video</title>
<style>
body{font:15px system-ui;margin:0;background:#111;color:#eee}main{max-width:1100px;margin:auto;padding:28px}
section{background:#1b1b1b;padding:18px;border-radius:12px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}
.scene{border:1px solid #333;padding:12px;border-radius:9px}.row{display:flex;gap:8px;flex-wrap:wrap}input,textarea,select,button{font:inherit;padding:9px;border-radius:7px;border:1px solid #444;background:#222;color:#eee}input,textarea,select{width:100%;box-sizing:border-box;margin:6px 0 12px}button{cursor:pointer}button:hover{background:#333}button:disabled{opacity:.5;cursor:wait}
pre{white-space:pre-wrap}.ok{color:#7ddc8b}.bad{color:#ff7777}.muted{color:#aaa}video{width:100%;max-height:500px;border-radius:9px;margin-top:10px}img{width:100%;border-radius:8px;margin-top:8px}audio{width:100%;margin-top:8px}.artifact{margin-top:10px;padding-top:8px;border-top:1px solid #333}.artifact a{color:inherit}
</style></head><body><main><h1>Local AI Video</h1><p class="muted">Local-only generation dashboard</p>
<section><h2>New project</h2><textarea id="prompt" rows="4" placeholder="Describe the video you want..."></textarea><div class="grid"><label>Duration <input id="duration" type="number" value="60" min="1"></label><label>Style <input id="style" value="cinematic"></label><label>Aspect ratio <input id="ratio" value="16:9"></label></div><button id="create" onclick="createProject()">Create project</button><pre id="createResult"></pre></section>
<section><h2>Projects</h2><div class="row"><button onclick="loadProjects()">Refresh</button></div><div id="projects" class="grid"></div></section>
<section id="detail" hidden><h2 id="title"></h2><div class="row"><button onclick="resumeProject()">Resume plan</button><button onclick="runQA()">Run QA</button><button onclick="startMediaJob()">Generate media in background</button></div><p id="jobStatus" class="muted">No background job submitted.</p><div id="jobs"></div><pre id="meta"></pre><section><h3>Timeline & subtitles</h3><div id="timeline" class="muted">Loading timeline...</div><div class="row"><a id="srt" hidden target="_blank">SRT</a><a id="vtt" hidden target="_blank">WebVTT</a></div></section><div id="scenes" class="grid"></div><h3>QA</h3><pre id="qa"></pre><h3>Final video</h3><video id="finalVideo" controls hidden></video></section>
<script>
let currentId=null;let jobPoll=null;
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(url,opt){const r=await fetch(url,opt);const t=await r.text();if(!r.ok)throw Error(t||r.status);return t?JSON.parse(t):null}
function setBusy(b){document.querySelectorAll('button').forEach(x=>x.disabled=b)}
async function createProject(){const out=document.querySelector('#createResult');out.textContent='Creating Director plan...';setBusy(true);try{const p=await api('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:document.querySelector('#prompt').value,duration:Number(document.querySelector('#duration').value),style:document.querySelector('#style').value,aspect_ratio:document.querySelector('#ratio').value})});out.textContent=JSON.stringify(p,null,2);await loadProjects();if(p.project_id)await openProject(p.project_id)}catch(e){out.textContent=e.message}finally{setBusy(false)}}
async function loadProjects(){const box=document.querySelector('#projects');try{const ps=await api('/api/projects');box.innerHTML=ps.length?ps.map(p=>`<div class="scene"><b>${esc(p.title)}</b><p>Status: ${esc(p.status)}</p><button onclick="openProject('${p.id}')">Open</button></div>`).join(''):'No projects yet.'}catch(e){box.textContent=e.message}}
async function openProject(id){currentId=id;try{const d=await api('/api/projects/'+id);document.querySelector('#detail').hidden=false;document.querySelector('#title').textContent=d.project.title;document.querySelector('#meta').textContent=JSON.stringify(d.project,null,2);document.querySelector('#scenes').innerHTML=d.scenes.map(s=>`<div class="scene"><b>Scene ${s.index}</b><p>${esc(s.visual_description)}</p><p class="muted">${esc(s.start_seconds)}s → ${esc((s.start_seconds+s.duration_seconds).toFixed(2))}s · ${esc(s.duration_seconds)}s</p><p>Status: ${esc(s.status)}</p><div class="row"><select id="stage-${s.id}"><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option></select><button onclick="regen('${s.id}',this)">Regenerate</button></div><div id="art-${s.id}"></div></div>`).join('');await refreshTimeline();await refreshQA();await renderArtifacts(d.scenes);await refreshJobs()}catch(e){alert(e.message)}}
async function renderArtifacts(scenes){await Promise.all(scenes.map(async s=>{const box=document.querySelector('#art-'+s.id);try{const d=await api('/api/projects/'+currentId+'/scenes/'+s.id+'/artifacts');const a=d.artifacts||{};let html='';if(a.image)html+=`<div class="artifact"><b>Image</b><img src="${esc(a.image.url)}" alt="Scene ${esc(s.index)} image"></div>`;if(a.audio)html+=`<div class="artifact"><b>Audio</b><audio controls src="${esc(a.audio.url)}"></audio></div>`;if(a.video)html+=`<div class="artifact"><b>Video</b><video controls src="${esc(a.video.url)}"></video></div>`;box.innerHTML=html||'<p class="muted">No generated media yet.</p>'}catch(e){box.textContent=e.message}}))}
async function refreshTimeline(){const box=document.querySelector('#timeline');try{const t=await api('/api/projects/'+currentId+'/timeline');const rows=(t.scenes||[]).map(s=>`<div>Scene ${esc(s.index)} · ${esc(s.start_seconds)}s → ${esc((s.start_seconds+s.duration_seconds).toFixed(2))}s · ${s.narration?esc(s.narration):'<span class="muted">no narration</span>'}</div>`).join('');box.innerHTML=rows||'Timeline has no scenes.';for(const f of ['srt','vtt']){const link=document.querySelector('#'+f);try{const r=await fetch('/api/projects/'+currentId+'/subtitles/'+f,{method:'HEAD'});link.hidden=!r.ok;link.href='/api/projects/'+currentId+'/subtitles/'+f}catch(_){link.hidden=true}}}catch(e){box.textContent='Timeline not available yet.'}}
async function refreshQA(){try{const q=await api('/api/projects/'+currentId+'/qa');document.querySelector('#qa').innerHTML=q.passed?'<span class="ok">PASS</span>':`<span class="bad">FAIL</span>\n${esc(JSON.stringify(q.failures,null,2))}`;const v=document.querySelector('#finalVideo');v.hidden=false;v.src='/api/projects/'+currentId+'/video';}catch(e){document.querySelector('#qa').textContent=e.message}}
async function runQA(){setBusy(true);try{await refreshQA();await refreshTimeline()}finally{setBusy(false)}}
async function resumeProject(){setBusy(true);try{await api('/api/projects/'+currentId+'/resume',{method:'POST'});await openProject(currentId)}catch(e){alert(e.message)}finally{setBusy(false)}}
async function regen(sid,button){const stage=document.querySelector('#stage-'+sid).value;button.disabled=true;button.textContent='Working...';try{await api(`/api/projects/${currentId}/scenes/${sid}/regenerate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage})});await openProject(currentId)}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent='Regenerate'}}
async function startMediaJob(){const box=document.querySelector('#jobStatus');box.textContent='Submitting background generation job...';try{const job=await api('/api/projects/'+currentId+'/jobs/media',{method:'POST'});box.textContent=`Job ${job.id}: ${job.state} (${job.completed_scenes}/${job.scene_count} scenes)`;pollJob(job.id)}catch(e){box.textContent='Job failed to submit: '+e.message}}
async function refreshJobs(){const jobs=await api('/api/projects/'+currentId+'/jobs');const box=document.querySelector('#jobs');box.innerHTML=jobs.length?jobs.slice(0,5).map(j=>`<div class="muted">Job ${esc(j.id)} · ${esc(j.state)} · ${esc(j.completed_scenes)}/${esc(j.scene_count)}${j.error?' · '+esc(j.error):''}</div>`).join(''):'<div class="muted">No background jobs.</div>';const active=jobs.find(j=>j.state==='queued'||j.state==='running');if(active)pollJob(active.id)}
async function pollJob(id){if(jobPoll)clearInterval(jobPoll);const check=async()=>{try{const j=await api('/api/jobs/'+id);document.querySelector('#jobStatus').textContent=`Job ${j.id}: ${j.state} (${j.completed_scenes}/${j.scene_count} scenes)`;await refreshJobs();if(['completed','failed','interrupted'].includes(j.state)){clearInterval(jobPoll);jobPoll=null;await openProject(currentId)}}catch(e){clearInterval(jobPoll);jobPoll=null}};await check();jobPoll=setInterval(check,2000)}
loadProjects();
</script></main></body></html>"""
